language: cpp
compiler:
  -gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install git
  - git clone https://github.com/snap-stanford/snap.git
  - cd snap
  - sudo make all
  - cd ..
  

script:
  -
